version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo apt-get update
            sudo apt-get install allure
      - run:
          name: Runnning tests phase 2 - 4
          command: |
            . venv/bin/activate
            pytest tests/test_phase_two.py -n 4 --alluredir ./test_results/api
            pytest tests/test_phase_four.py --alluredir ./test_results/web
          when: always
      - store_artifacts:
          path: ./test_results
          destination: prefix
      - store_test_results:
          path: ./test_results